name: GitHub Snake Contributer Game

on:
    # Schedule workflow to run to refresh the snake game
    schedule:
        - cron: '0 0 * * *'
    # Allow manual trigger of workflow for instant update
    workflow_dispatch:
    # Or trigger the workflow on pushes to any branch in this repository
    push:

jobs:
    generate_snake:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Generate snake game
              uses: Platane/snk@v3
              with:
                # GitHub username to generate the animation for
                github_user_name: ${{ github.repository_owner }}
                # Define the output files and their configurations
                outputs: |
                    dist/github-snake.svg
                    dist/github-snake-dark.svg?palette=github-dark
                    dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

            - name: Deploy to branch
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GIT_TOKEN }}
                publish_dir: ./dist
                publish_branch: output
                # Optionally, you can set a custom commit message
                commit_message: "Update snake animation [skip ci]"
